import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button, Typography } from "@mui/material";
import { input } from "@/styles";
import Link from "next/link";
import { CustomInput } from "@/components";
import { Box } from "@mui/system";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Typography variant="h1" component="h1" sx={{ marginBottom: "25px" }}>
          Alarmify
        </Typography>
        <Image
          alt="logo"
          src="/alarm.png"
          width={100}
          height={100}
          style={{ marginBottom: "60px" }}
        />
        <CustomInput label="Usuario" type="email" variant="outlined" />
        <CustomInput
          label="Contraseña"
          type="password"
          variant="outlined"
          sx={{ marginBottom: "80px", marginTop: "40px" }}
        />
        <Link href="/inicio" style={{ textDecoration: "none" }}>
          <Button
            variant="contained"
            sx={{
              backgroundColor: "#EEE5E9",
              color: "black",
              width: "229px",
              height: "61px",
              textTransform: "none",
            }}
          >
            {" "}
            Iniciar sesión{" "}
          </Button>
        </Link>
        <Box sx={{ height: "100px" }}></Box>
        <Link href="/crear-cuenta" style={{ color: "white" }}>
          Crear cuenta
        </Link>
      </main>
    </>
  );
}
